BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX XX XX XXXXXXBBBBBBBB

BBBBB BBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    

    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    X
                 XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    X
                 XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXX X XXXXX XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    X
                 XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXX
    XXXXXX

XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX  XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        
        XXX XXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXX
            BBB BBBB BB BBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB  
            BBBBBB
        XXXXXX
        

        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXXXXXXXXXX
                    XXXXXXXXBBB BBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
                
            XXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXBBB BBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                XBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX  XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

XXXXXX
BBBBBBBB
