BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXX XXXXXXXXXX XXX XXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXXXX

        XXXXXXXXXX XXX XX XXXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB