# Generated by Django 4.1.4 on 2023-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_account_adress_remove_account_prova_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
