# Generated by Django 4.1.4 on 2022-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_rename_name_category_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(),
        ),
    ]
