# Generated by Django 4.1.7 on 2023-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='titol',
            field=models.TextField(default='f{product}'),
        ),
    ]
