# Generated by Django 4.1.7 on 2023-03-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_titol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titol',
            new_name='titulo',
        ),
    ]
