# Generated by Django 4.1.7 on 2023-03-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='titulo',
        ),
    ]
