# Generated by Django 4.1.7 on 2023-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_review_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.TextField(default='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
