# Generated by Django 4.1.7 on 2023-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_review_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.TextField(default=''),
        ),
    ]
