# Generated by Django 4.1.7 on 2023-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagecategory',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
