# Generated by Django 4.1.4 on 2023-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_imagecategory_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='thumbnail',
            new_name='image_size',
        ),
    ]
