# Generated by Django 4.1.4 on 2023-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
