# Generated by Django 4.1.7 on 2023-04-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('orden',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AddField(
            model_name='category',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_retail',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unidades',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categorias/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/marcas/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
