# Generated by Django 4.1.7 on 2023-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10),
        ),
    ]
