# Generated by Django 4.1.7 on 2023-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
