# Generated by Django 4.1.7 on 2023-04-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
