# Generated by Django 4.1.7 on 2023-04-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_variant_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='thumbnail',
        ),
    ]
