# Generated by Django 4.1.7 on 2023-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_variant_size_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
