# Generated by Django 4.1.7 on 2023-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='precio_retail',
            field=models.FloatField(null=True),
        ),
    ]
