# Generated by Django 4.1.7 on 2023-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_variant_precio_retail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
