# Generated by Django 4.1.4 on 2023-04-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_variant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
    ]
