# Generated by Django 4.1.7 on 2023-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_color_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
    ]
