# Generated by Django 4.1.7 on 2023-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_remove_product_image_id_remove_variant_image_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image_id',
            field=models.IntegerField(null=True),
        ),
    ]
