# Generated by Django 4.1.7 on 2023-05-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_image_remove_variant_image_variant_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
