# Generated by Django 4.1.7 on 2023-05-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
