# Generated by Django 4.1.7 on 2023-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.IntegerField(null=True),
        ),
    ]
