# Generated by Django 4.1.4 on 2023-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_extraimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='sizes_shoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
