# Generated by Django 4.1.4 on 2023-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_size_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes_shoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
