# Generated by Django 4.1.7 on 2023-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_product_sizes_shoes_alter_variant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('orden', models.IntegerField(default=0)),
                ('url_share', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/marcas/')),
            ],
            options={
                'verbose_name_plural': '99 - Red Socials',
                'ordering': ['orden'],
            },
        ),
    ]
