# Generated by Django 4.1.7 on 2023-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_redsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='url_share',
            field=models.URLField(blank=True, null=True),
        ),
    ]
