# Generated by Django 4.1.7 on 2023-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_redsocial_url_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/RedSocial/'),
        ),
    ]
