# Generated by Django 4.1.7 on 2023-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_alter_redsocial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
