# Generated by Django 4.1.7 on 2023-07-15 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_remove_product_desc_alter_product_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
