# Generated by Django 4.1.7 on 2023-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_product_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
