# Generated by Django 4.1.4 on 2023-08-17 18:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_alter_product_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraimage',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='product',
            name='sexo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('nino', 'nino'), ('nina', 'nina')], max_length=30, null=True),
        ),
    ]
