# Generated by Django 4.1.4 on 2023-08-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_extraimage_nombre_variant_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraimage',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='nombre',
        ),
    ]
