# Generated by Django 4.1.4 on 2023-08-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_remove_extraimage_nombre_remove_variant_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nombre',
        ),
    ]
