# Generated by Django 4.1.4 on 2023-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_image_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
