# Generated by Django 4.1.4 on 2023-08-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_product_popular_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popular_rating',
        ),
    ]
