# Generated by Django 4.1.4 on 2024-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
