# Generated by Django 4.1.4 on 2024-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_alter_category_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nombre_ca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
