# Generated by Django 4.1.4 on 2024-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_category_nombre_ca_alter_category_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre_ca',
            field=models.CharField(max_length=255),
        ),
    ]
