# Generated by Django 4.1.4 on 2024-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_product_nombre_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.TextField(default='', verbose_name='Título'),
        ),
    ]
