# Generated by Django 4.1.4 on 2024-04-10 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_alter_review_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
