# Generated by Django 4.1.4 on 2024-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_product_descripcion_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estado_producto',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Oculto', 'Oculto')], default='Publicado', max_length=30),
        ),
    ]
