BB BBBBBBBBBBB B B
BBBB BBBBBBBBBBB
XX XXXXXXBBB BBBBBBX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXXX XXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
        BBB BBBB BB BBBB
            BB BBBBBBBBBBBBBBBB B B
                XXX XXXXXXXXXXXXX
            BBBBB
            XXXX XXXXXXXXX
                XXXXX XXXXXXXXXXX XXXX XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXX
                    XXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                            
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                            
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFXXXXXXX
                                    XXXXXXXXXXXXXXX XXXXXXX
                            
                                XXXXXXX

                            XXXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB B
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFF XXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXFFFFFFFFFFFFF XXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX FFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFF XXXXXXX
                                BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                                BBBBB
                            XXXXXXX
                            
                        XXXXXXX
                        
                    XXXXXXX
                XXXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXFFFFFFFFFFFFF XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
            XXXXXXX XXXXXXBBB BBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX X XXXXXX X XXXXXX X XXXXX XXXXXXXX XXXXXXXX X XXXXXX X XXXXXX X XXXXX XXX XX
                    XXXXXX 
                    XX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXX
BBBB
XX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
BBBBB