BBBB BBBBBBBBBBB
BB BBBB
XXXX XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXX XXXX XXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXX
    
        XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  FFFFFFFFFXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
                        XX 
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                        XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBB BBBBBBBBX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                        X
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXX XXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX X X XXXXXXXX XXXXXXXXXX X X XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX X X XXXX XXXXX XXXXXXX
                                    XXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                        XX 
                            XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX
                            XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBB BBBBBBBBBBBX
                            XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX
                        X
                              XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXX  XXXXXXXXXX X XX XXX  XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX  XXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX
                        XXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XX 
                            XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX
                            XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBB BBBBBBBBBBBX
                            XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX
                        X
                            XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXX  XXXXXXXXXX X XX XXX  XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX  XXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XX  XXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX
                        XXXX
                    XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB B
                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFF XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX FFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFF XXXXXXX
                            BBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
    
            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                XX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBB BBBBBBBBX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                X
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX X X XXXXXXXX XXXXXXXXXX X X XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX X X XXXX XXXXX XXXXXXX
                            XXXXXX
                            XXXXXX
                            XXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX  
    
    XXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
    
XXXXXX


BBBBB