BBBB BBBBBBBBBBB
BBBB BBBBBB
XXXXXXX
    XXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X XXXX XXXXX XXXXXX XXXXXX XXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXX
                    XXXX  XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB BB BBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                    BBBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                    BBBBB

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB BB BBB
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                        BBBB
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFF XXXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXX
    
            XXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXX XXXXXXXXXXX XXXXXXXXX XX XXXXXX X XX XXXXXXXX XX XXXXXXXXXX XX XXXXXXX XXXXXX
                    XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            
            XX  
                XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                X
                XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X XXXX XXXXX XXXXXX XXXXXX XXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
            XXXX
            XX  
                XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                X
                XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X XXXX XXXXX XXXXXX XXXXXX XXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX  
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXX
                    X
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX
                        XXXXX
                            XXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X XXXX XXXXX XXXXXX XXXXXX XXXXX
                            XXXXXX
                        XXXXXX
                        XXXX  XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                    
                XXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX X
                XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXX
                    XXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XXXX  XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X XXXX XXXXX XXXXXX XXXXXX XXXXX
                XXXXXX
                XXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX

            XXXXX
                BBB BBBB BB BBBB
                BB BBBBBBBBBBBBBBBB B B
                    XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                BBBBB
                BB BBBB
                XX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXX XXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                
                                            XXXXXX
                                            XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX FFFFFFFFFXXXXXXX

                                        XXXXXXX
                                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB B
                                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFF XXXXXXX
                                            XXXX XXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                                            BBBB
                                            XXXX XXXXXXXXXFFFFFFFFFFFFF XXXXXXX
                                            BBBBB
                                        XXXXXXX
                                    XXXXXXX
                                XXXXXX
                            
                            XXXXXXX
                        XXXXXXX
                    XXXX
                BBBBB
                BBBBBB
                XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX
XXXXXX