BB BBBBBBBBBBB B B
XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
        FFFFFF
    XXXXXXX
XXXX
BBBB
XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
        X
    XXXXXXX
XXXX
BBBBB