BB BBBBBBBBBBB B B
BBBB BBBBBBBBBBB
XX XXXXXXBBB BBBBBBX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX X XXXXXX X XXXXXX X XXXXX XXXXXXXX XXXXXXXX X XXXXXX X XXXXXX X XXXXX XXX XX
    XXXXXX                          
XXXX
XX XXXXXXBBB BBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
        FFFFFF
    XXXXXXX
XXXX
BBBB
XX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX X XXXXXX X XXXXXX X XXXXX XXXXXXXX XXXXXXXX X XXXXXX X XXXXXX X XXXXX XXX XX
    XXXXXX                          
XXXX
XX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
        X
    XXXXXXX
XXXX
BBBBB

XXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX