XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X X XXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXX
  X

  XXXXXX X
      XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXX X
      XX X
          XXXXXXXXXX XXXXXXXXXXXXX
      X

      XXXX X
          XXXXXXXXXX XXXXXXXXXXXXXXX
      X
  X

  XXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX XXX XXX XXXXX XXX XXXXXXX XX XX XXXXXX
    XXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXXX XXXXXXXX
  X

  XXXXXXXXX
  XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXX
  X
  XXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXX X X X XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX
  X
  XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXX
    XXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXX X X XXXXXXX
    XXXX XXXXXXX
    XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXX XXXX XXXXX
  X
  XXXXXXXXXXXXXX X
    XXXXXX XXXXXXX
    XXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX X XXXXXX XXXXXX XX
    XXXX XXXXXXX
    XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX
    XXXXXXXXXXXXXXXXX XXX XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXX XXXXXXX X
    XX X
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXX
    X
    XXXX X
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXX
    X
  X
  XXXXXXXXXX XXXXXXX X
    XX X
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXX
    X
    XXXX X
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXX
    X
  X


XXXXXXXX