# Generated by Django 4.1.4 on 2023-11-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastosprovincia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Gastos_Provincia'},
        ),
    ]
