# Generated by Django 4.1.4 on 2022-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='provincia',
            field=models.CharField(default='B', max_length=255),
        ),
    ]
