# Generated by Django 4.1.4 on 2022-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_place_order_city_order_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provincia',
            field=models.CharField(max_length=255),
        ),
    ]
