# Generated by Django 4.1.4 on 2023-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitem_envio_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
