# Generated by Django 4.1.4 on 2023-11-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('id_tel', models.CharField(blank=True, max_length=250, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
