# Generated by Django 4.1.4 on 2023-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_clueinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clueinfo',
            options={'verbose_name_plural': '1 - ClueInfo'},
        ),
    ]
