# Generated by Django 4.1.4 on 2024-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_clueinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detalles_envio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
