# Generated by Django 4.1.4 on 2024-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_detalles_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estado_pago',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded')], default='Succeeded', max_length=20),
        ),
    ]
