# Generated by Django 4.1.4 on 2024-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado_pago',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded')], default='succeeded', max_length=20),
        ),
    ]
